var UnitTypes = [
        {
            id: 'archer',
            name: 'archer',
            image: 'archer.png',
            attack: 10,
            defense: 1,
            canShoot: true,
            gold: 5,
            movements: 1,
        },
        {
            id: 'axeman',
            name: 'axeman',
            image: 'axeman.png',
            attack: 14,
            defense: 3,
            canShoot: false,
            gold: 6,
            movements: 1,
        },
        {
            id: 'tribalwarrior',
            name: 'tribal warrior',
            image: 'tribalwarrior.png',
            attack: 13,
            defense: 2,
            canShoot: false,
            gold: 8,
            movements: 1,
        },
        {
            id: 'snake',
            name: 'snake',
            image: 'snake.png',
            attack: 14,
            defense: 1,
            canShoot: false,
            gold: 2,
            movements: 1,
        },
        {
            id: 'wolf',
            name: 'wolf',
            image: 'wolf.png',
            attack: 12,
            defense: 2,
            canShoot: false,
            gold: 3,
            movements: 2,
        },
        {
            id: 'peasant',
            name: 'peasant',
            image: 'peasant.png',
            attack: 10,
            defense: 1,
            canShoot: false,
            gold: 9,
            movements: 1,
        },
        {
            id: 'halfling',
            name: 'halfling',
            image: 'halfling.png',
            attack: 12,
            defense: 2,
            canShoot: false,
            gold: 12,
            movements: 1,
        },
        {
            id: 'dwarfaxe',
            name: 'dwarf',
            image: 'dwarfaxe.png',
            attack: 15,
            defense: 5,
            canShoot: false,
            gold: 15,
            movements: 1,
        },
        {
            id: 'lion',
            name: 'lion',
            image: 'lion.png',
            attack: 15,
            defense: 4,
            canShoot: false,
            gold: 4,
            movements: 2,
        },
        {
            id: 'insectman',
            name: 'insect man',
            image: 'insectman.png',
            attack: 14,
            defense: 3,
            canShoot: true,
            gold: 13,
            movements: 2,
        },
        
    ];
